#============
[application]
#============

# App (Project) Name
name = "cognitive"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

#========
[web.app]
#========

# HTML title tag content
title = "Cognitive"

#============
[web.watcher]
#============

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = [ "src", "assets" ]

#=============
[web.resource]
#=============

# It includes `assets` in web platform.
# CSS style file
style = [ "/assets/main.css" ]

# Javascript code file
script = []

#=================
[web.resource.dev]
#=================

# Javascript code file
# serve: [dev-server] only
script = []
